### ISSUE TITLE
Adhering to the DCC++ GPL License

### ISSUE THREAD

**Issue by FrightRisk** [positron96/LocoNetControlStation#21] opened 2022-05-18 20:47 UTC
Hi Paul, I am not sure how else to contact you. We posted on your youtube channel and were hoping to see if you would be interested in talking with or joining our team. We are doing some interesting things with Loconet and have advanced the original DCC++ way beyond the original code. You may not be aware of licensing issues so we are happy to help you with that as well. Please email me at support@dcc-ex.com give me a chance to persuade you to join us, even if just for a quick discussion.

Kind Regards
 Fred
Fred Decker
DCC-EX

**Comment by positron96** [comment] 2022-05-20 05:53
Hi. 
For some reason, I haven't seen and still don't see anything on youtube channel, so it's good that you've written here. 
Since you opened and issue about GPL, can you state the issue in more detail here? As for discussion about joining, I'll send you an email.

**Comment by habazut** [comment] 2022-06-17 08:19
Hi!

The issue is that by copying GPLed source code you have created what legally is called a derived work. If you want to distribute such a derived work it is only allowed to distribute that under the GPL or another license that incorporates the rights of the GPL. If you do not want to publish your work under the GPL you may not use the GPLed source either. You can of course dual license your work if you want that.

When inspecting the source code it is obvious that it is a copy of the GPLed original as some errors were copied as well.

Regards,
Harald.

**Comment by positron96** [comment] 2022-06-18 07:32
Hello, thank you for the explanation. 

Let me provide some clarifications on the issue: my project is based on DCC++ project (https://github.com/DccPlusPlus/BaseStation), as stated in project description. I've checked it thoroughly and nowhere in the sources of DCC++ I see any mention of GPL. If I missed anything, please provide links to files that state that DCC++ is GPL-licensed.

**Comment by positron96** [comment] 2022-08-14 06:15
I am closing the issue since there has been no further communication. Feel free to post here and reopen if needed.

**Closed** 2022-08-14 06:16 UTC
